language: php

php:
  - 5.3
  - 5.4

branches:
  only:
    - master

before_script:
    - pyrus channel-discover pear.php-tools.net
    - pyrus install pat/vfsStream-beta
    - phpenv rehash
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install